### ISSUE TITLE
TCIA data (nii format) and tumor ground truth

### ISSUE THREAD

**Issue by JunMa11** [khuhm/deep-kidney-cancer#1]
Dear @khuhm ,

Thanks for sharing the great work.

Could your share the TCIA data (nii format) and tumor ground truth?

Best regards,
Jun

**Comment by khuhm** [comment]
Dear @JunMa11,

Thanks for your interest in our work.

Do you mean the ground truth of tumor subtypes? (ccRCC, pRCC, chRCC)

Best regards,
Kwang-Hyun

**Comment by JunMa11** [comment]
Dear @khuhm ,

Thanks for your reply very much.

I mean the segmentation ground truth:)

![image](https://user-images.githubusercontent.com/19947331/123260847-a1822080-d528-11eb-890c-76b7ee35e8eb.png)

Best regards,
Jun

**Comment by khuhm** [comment]
Dear @JunMa11,

The TCIA data was used only for the testing of the model, and thus segmentation annotation was not performed.

Annotation of segmentation masks was performed on our in-house dataset, where some restrictions exist.

We are looking for a way to share this data, but it is not currently publicly available.

Best regards,
Kwang-Hyun

**Comment by JunMa11** [comment]
Got it. Thanks for your reply very much.
